springfox.documentation.swagger.v2.path: /api-docs
spring.jackson.date-format: org.garen.tourist.swagger.RFC3339DateFormat
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

spring:
  profiles:
    active: local