mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.garen.tourist.mybatis.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.104.170.186:3306/mc?mc=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 7Tf88ga2pU
      type: com.zaxxer.hikari.HikariDataSource
  redis:
      database: 0
      host: localhost
      port: 6379
      password:
      timeout: 6000
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
server:
  port: 9092
  tomcat:
    max-threads: 1024
    uri-encoding: utf-8